"""Seed lexicons for bootstrapping signal detectors."""

from __future__ import annotations

from .signals import Signal

SEED_KEYWORDS = {
    Signal.GOOD: {
        " wholesome",
        "good vibes",
        "feel good",
        "heartwarming",
        "uplifting",
        "inspired",
        "asmr",
        "puppy",
        "kitten",
        "cozy",
        "blessed",
        "family time",
        "comfort",
        "satisfying",
    },
    Signal.BAD: {
        "trigger warning",
        "tw ",
        "problematic",
        "scam",
        "dangerous",
        "bully",
        "cancelled",
        "hate",
        "violence",
        "weapon",
        "abuse",
        "threat",
        "unalive",
        "exposed",
        "call-out",
    },
    Signal.TEA: {
        "drama",
        "tea",
        "storytime",
        "spill",
        "receipts",
        "messy",
        "clapback",
        "beef",
        "feud",
        "cheating",
        "liar",
        "callout",
        "exposed",
    },
    Signal.WEIRD: {
        "weirdcore",
        "dreamcore",
        "traumacore",
        "liminal",
        "analog horror",
        "backrooms",
        "uncanny",
        "surreal",
        "cursed",
        "oddly specific",
        "glitch",
        "void",
        "doppelganger",
    },
}

# Keyword sets used to trigger conflict-specific heuristics.
COUNTERSPEECH_HINTS = {
    "refuting",
    "calling out",
    "exposing",
    "talking about",
    "discussing",
    "addressing",
    "said",
    "saying",
    "explained",
    "explaining",
    "responding",
    "response",
    "debunk",
    "debunking",
    "my story",
    "sharing",
}

KARPMAN_HINTS = {
    "it's all your fault",
    "it's your fault",
    "always",
    "never",
    "blame",
    "blaming",
    "victim",
    "poor me",
    "why would you",
    "i can't believe you",
    "should",
    "must",
    "rescue",
    "saving",
    "save you",
    "i have to help",
}

DISTURBING_HINTS = {
    "nightmare",
    "horror",
    "creepy",
    "unnerving",
    "disturbing",
    "cursed",
    "unsettling",
    "panic",
    "fear",
}
